setwd("C:/Users/harsh/OneDrive/Documents/r scripts practice/")

df = read.csv('hypothyroid (1).csv')
head(df)

# Data Preprocessing
colnames(df)
dim(df)

summary(df)

library(skimr)
skim(df)

# Value counts for each column in the Dataset
value_counts <- lapply(df, table)
value_counts

# Print unique values of each column
unique_values <- lapply(df, unique)
for (col in names(unique_values)) {
  cat(col, ":", unique_values[[col]], "\n\n")
}

# Print the null values in each column
colSums(is.na(df))

# DATA CLEANING

invalid_counts <- sapply(df, function(x) sum(x == "?", na.rm = TRUE))
# Print only columns where '?' is present
invalid_counts[invalid_counts > 0]

# Dropping the TBG column --> The Column loaded with Invalid Values
library(dplyr)
df <- df %>% select(-TBG)
colnames(df)
dim(df)

head(df[, c("T4U_measured", "T4U")])
# Looking to the dataset, we can see that some columns are with true and false value are just the indication that whether the next column has values or not.

# Lets drop such columns 
df <- df %>% select(-c(TSH_measured, T3_measured, TT4_measured, T4U_measured, FTI_measured, TBG_measured))
colnames(df)
dim(df)

# Replace the '?' values with null representation NA
df <- df %>% mutate_all(~ ifelse(. == "?", NA, .))

# Verify if any columns still contain ? values
counts <- sapply(df, function(x) sum(x == "?", na.rm = TRUE))
print(counts)

# Check if their are any missing values
colSums(is.na(df))

# DATA ENCODING
# Converting categorical data to numeric data 
df$sex <- ifelse(df$sex == "F", 0, 1)

df <- data.frame(lapply(df, function(x) {
  if (length(unique(x)) == 2) {
    return(ifelse(x == "f", 0, ifelse(x == "t", 1, x)))
  } else {
    return(x)
  }
}))

# One Hot Encoding for 'Referral Source' column
library(fastDummies)
df <- dummy_cols(df, select_columns = "referral_source", remove_first_dummy = FALSE)
colnames(df)

# Now lets do Label encoding for 'class' column 
df$Class <- as.numeric(factor(df$Class)) - 1
sample(df$Class)

value_counts <- lapply(df, table)
value_counts

# Data Imputation - Treating missing values
library(VIM)
str(df)

# Step 1: Convert specific columns to numeric (float)
colnames_numeric <- setdiff(colnames(df), "referral_source")
colnames_numeric
df[colnames_numeric] <- lapply(df[colnames_numeric], function(x) {
  x <- as.character(x)  
  x[x == "?"] <- NA     
  as.numeric(x)         
})
str(df)

# Step 2: Separate numeric and categorical columns
colnames_numeric <- setdiff(colnames(df), c("sex","referral_source"))
df_num <- df[colnames_numeric]  
df_cat <- df['sex']  

# Step 3: Apply KNN Imputation (k=10)
df_imputed <- kNN(df_num, k = 10)

# Step 4: Remove extra "_imp" columns generated by kNN()
df_imputed <- df_imputed[, names(df_num)]
colnames(df_imputed)

# Step 5: Merge categorical columns back with imputed numeric data
new_df <- cbind(df_cat, df_imputed)

# Print structure of the final dataframe
str(new_df)

colSums(is.na(new_df))

# Print unique values of each column
unique_values <- lapply(new_df, unique)
for (col in names(unique_values)) {
  cat(col, ":", unique_values[[col]], "\n\n")
}

# DATA VISVALIZATION
library(ggplot2)

# Count occurrences of each class
counts <- table(new_df$Class)
df_counts <- as.data.frame(counts)
colnames(df_counts) <- c("Class", "Count")

# Create bar plot
# 0: Compensated Hypothyroid; 1: Negative; 2: Primary Hypothyroid; 3: Secondary Hypothyroid.
ggplot(df_counts, aes(x = Class, y = Count)) +
  geom_bar(stat = "identity", fill = "orange", color = "black") +
  labs(title = "Class Distribution", x = "Class", y = "Count") +
  theme_minimal()

# Thyroid occurrences based on sex
ggplot(new_df, aes(x = Class, fill = as.factor(sex))) +
  geom_bar(position = "stack") + 
  labs(title = "Thyroid Occurrence on the Basis of Sex",
       x = "Class",
       y = "Count",
       fill = "Sex") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Thyroid occurrences based on sick
ggplot(new_df, aes(x = Class, fill = as.factor(sick))) +
  geom_bar(position = "stack") +  
  labs(title = "Thyroid Occurrence on the Basis of Sickness",
       x = "Class",
       y = "Count",
       fill = "Sick") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  

# Thyroid occurrences based on Pregnancy
ggplot(new_df, aes(x = Class, fill = as.factor(pregnant))) +
  geom_bar(position = "stack") +  
  labs(title = "Thyroid Occurrence on the Basis of Pregnancy",
       x = "Class",
       y = "Count",
       fill = "Pregnant") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Thyroid occurrences based on Thyroid Surgery
ggplot(new_df, aes(x = Class, fill = as.factor(thyroid_surgery))) +
  geom_bar(position = "stack") +  
  labs(title = "Thyroid Occurrence on the Basis of Thyroid Surgery",
       x = "Class",
       y = "Count",
       fill = "Thyroid Surgery") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  

# Thyroid occurrences based on Goitre
ggplot(new_df, aes(x = Class, fill = as.factor(goitre))) +
  geom_bar(position = "stack") +  
  labs(title = "Thyroid Occurrence on the Basis of Goitre",
       x = "Class",
       y = "Count",
       fill = "Goitre") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Thyroid occurrences based on Tumor
ggplot(new_df, aes(x = Class, fill = as.factor(tumor))) +
  geom_bar(position = "stack") + 
  labs(title = "Thyroid Occurrence on the Basis of Tumor",
       x = "Class",
       y = "Count",
       fill = "Tumor") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Type of Thyroid vs T3
boxplot(T3 ~ Class, data=new_df,
        main = "Type of Thyroid vs T3",
        xlab = "Type of Thyroid",
        ylab = "T3")

# Type of Thyroid vs TT4
boxplot(TT4 ~ Class, data=new_df,
        main = "Type of Thyroid vs TT4",
        xlab = "Type of Thyroid",
        ylab = "TT4")

# Type of Thyroid vs T4U
boxplot(T4U ~ Class, data=new_df,
        main = "Type of Thyroid vs T4U",
        xlab = "Type of Thyroid",
        ylab = "T4U")

# Type of Thyroid vs TSH
boxplot(TSH ~ Class, data=new_df,
        main = "Type of Thyroid vs TSH",
        xlab = "Type of Thyroid",
        ylab = "TSH")

# Type of Thyroid vs FTI
boxplot(FTI ~ Class, data=new_df,
        main = "Type of Thyroid vs FTI",
        xlab = "Type of Thyroid",
        ylab = "FTI")


# Data Balance
new_df <- na.omit(new_df)
colSums(is.na(new_df))

# Install and load the necessary package
library(caret)
x <- new_df[, !names(new_df) %in% "Class"] 
y <- new_df$Class                           

y <- as.factor(y)

data <- cbind(x, y)

# Perform random oversampling using the `upSample` function from caret
balanced_data <- upSample(x = data[, -ncol(data)], 
                          y = data$y,             
                          yname = "y")

# Split the balanced data back into x and y
x_sampled <- balanced_data[, -ncol(balanced_data)]
y_sampled <- balanced_data['y']

dim(x_sampled)
colSums(is.na(x_sampled))

dim(y_sampled)
unique_values <- lapply(y_sampled, unique)
unique_values

library(ggplot2)

# Ensure y_sampled is a factor (categorical variable)
df_y <- data.frame(Class = as.factor(y_sampled[[1]]))

ggplot(data = df_y, aes(x = Class, fill = Class)) +
  geom_bar() +
  labs(title = "Class Distribution after Sampling", x = "Class", y = "Count") +
  theme_minimal()


# Set a random seed for reproducibility
set.seed(25641)

# Splitting data: 80% train, 20% test
y_sampled <- as.factor(unlist(y_sampled))
train_index <- createDataPartition(y_sampled, p = 0.8, list = FALSE)

# Creating train and test datasets
X_train <- x_sampled[train_index, ]
X_test  <- x_sampled[-train_index, ]
y_train <- y_sampled[train_index]
y_test  <- y_sampled[-train_index]

dim(X_train)
dim(X_test)
summary(y_train)
summary(y_test)



# ******************* LOGISTIC REGRESSION ******************* 
# Load necessary library
library(nnet)

# Define the logistic regression function for multiclass classification
log_classifier <- function(X_train, X_test, y_train, y_test) {
  train_data <- data.frame(X_train, y = y_train)
  log_model <- multinom(y ~ ., data = train_data)
  log_pred <- predict(log_model, newdata = data.frame(X_test))
  cm <- confusionMatrix(log_pred, as.factor(y_test))
  acc <- cm$overall['Accuracy']
  train_score <- mean(predict(log_model, newdata = train_data) == y_train)
  test_score <- mean(log_pred == y_test)
  return(list(
    Accuracy_Score = acc,
    Train_Score = train_score,
    Test_Score = test_score,
    Confusion_Matrix = cm$table
  ))
}
results <- log_classifier(X_train, X_test, y_train, y_test)
print("Logistic Regression Results \n")
print(results)


# ******************* RANDOM FOREST CLASSIFIER ******************* 
forest_classifier <- function(X_train, X_test, y_train, y_test) {
  library(randomForest) 
  library(caret)
  
  train_data <- data.frame(X_train, y_train)
  test_data <- data.frame(X_test, y_test)
  
  # classifier_forest <- randomForest(y_train ~ ., data = train_data, importance = TRUE, maxnodes = 10)
  classifier_forest <- randomForest(y_train ~ ., data = train_data, importance = TRUE)
  rf_pred <- predict(classifier_forest, newdata = X_test)
  
  cm <- table(y_test, rf_pred)
  acc <- sum(diag(cm)) / sum(cm)
  
  train_score <- mean(predict(classifier_forest, newdata = X_train) == y_train)
  test_score <- mean(rf_pred == y_test)
  
  cm_caret <- confusionMatrix(as.factor(rf_pred), as.factor(y_test))
  precision <- cm_caret$byClass["Pos Pred Value"]
  recall <- cm_caret$byClass["Sensitivity"]
  # f1_score <- 2 * (precision * recall) / (precision + recall)
  
  
  importance_vals <- importance(classifier_forest, type = 1)
  sorted_importance <- importance_vals[order(importance_vals, decreasing = TRUE), , drop = FALSE]
  # rf_p_values <- apply(importance_vals, 1, function(x) 1 - pnorm(abs(x)))
  
  
  return(list(
    Model = classifier_forest,
    Accuracy_Score = acc,
    Train_Score = train_score,
    Test_Score = test_score,
    Confusion_Matrix = cm,
    # P_Values = rf_p_values,
    sorted_importance
  ))
}
results <- forest_classifier(X_train, X_test, y_train, y_test)
rf_model = results$classifier_forest
print("Random Forest Classifier Results ")
print(results)




# ******************* LIME ******************* 
# Define model_type method for randomForest
model_type.randomForest <- function(x, ...) {
if (x$type == "classification") {
     return("classification")
   }
   else if (x$type == "regression") {
     return("regression")
   }
   else {
     return("classification")
   }
 }

 # Define predict_model method for randomForest
 predict_model.randomForest <- function(x, newdata, type = "raw", ...) {
   pred <- predict(x, newdata = newdata, type = "prob")
   if (type == "prob") {
     return(as.data.frame(pred))
   }
   else if (type == "raw") {
     return(predict(x, newdata = newdata, type = "response"))
   }
 }

library(randomForest)
library(lime)

# Train the Random Forest model
results <- forest_classifier(X_train, X_test, y_train, y_test)
classifier_forest <- results$Model  
train_data <- data.frame(X_train)
explainer <- lime(train_data, classifier_forest, bin_continuous = FALSE, quantile_bins = FALSE)
instance_to_explain <- X_test[1999, , drop = FALSE]
# instance_to_explain <- X_train[9191, , drop = FALSE]
explanation <- explain(instance_to_explain, explainer, n_features = 5, n_labels = 1)
print(explanation)
plot_features(explanation)




